title: "A Toca"
email: atoca@gmail.com
timezone: Etc/GMT-3
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.ico"
author: Afonso
paginate: 30
disqus: "demowebsite"
locale: pt_br
lang: pt_br
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Afonso da Fonseca Braga
    display_name: Afonso
    avatar: "assets/images/sal.png"
    email: afonso.braga@engenharia.ufjf.br
    web:
    twitter:
    description: "lalala"

# Social
social:
  instagram: https://www.instagram.com/
  facebook: https://www.facebook.com/
  twitter: https://twitter.com/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
